### ISSUE TITLE
Problems handling paths with spaces in filenames

### ISSUE THREAD

**Issue by yairchu** [ElastiLotem/resolve-trivial-conflicts#2]
git status:

    ...
    Unmerged paths:
      (use "git add <file>..." to mark resolution)
    
    	both modified:   examples/audio plugin demo/Source/PluginProcessor.h

resolve-trivial-conflicts:

    resolve-trivial-conflicts: .../examples/audio: openFile: does not exist (No such file or directory)

**Comment by ElastiLotem** [comment]
Fixed
