### ISSUE TITLE
Handle submodule conflicts

### ISSUE THREAD

**Issue by yairchu** [ElastiLotem/resolve-trivial-conflicts#5]
Currently shows:

    resolve-trivial-conflicts: <SUBMODULE-PATH>: openFile: inappropriate type (is a directory)

**Comment by ElastiLotem** [comment]
This was fixed by noam in PR #7

**Comment by ElastiLotem** [comment]
Note that there's nothing smart being done when conflicted submodules exist. Any ideas for what could help here?

**Comment by yairchu** [comment]
Not sure what git itself does with submodules, but if one's submodule is a fast-forward of the other then it's a trivial conflict.

As for non-trivial conflicts, it should probably propagate to a conflict in the submodule, and then resolve all the trivial conflicts there.. though maybe it's not so trivial

**Comment by ElastiLotem** [comment]
Then I need to decide if I want to rebase or merge in the submodule :-(

Maybe can have a flag --merge or so that does this.

**Comment by yairchu** [comment]
If the conflicts are during a rebase, default is rebase as well. If they are during merge - merge is the default..

**Comment by ElastiLotem** [comment]
Any way to detect what's the "current" operation?

If the conflicts are during a rebase, default is rebase as well. If they
are during merge - merge is the default..

—
Reply to this email directly or view it on GitHub
<https://github.com/ElastiLotem/resolve-trivial-conflicts/issues/5#issuecomment-144033913>
.

**Comment by yairchu** [comment]
when rebasing, "git status" says "You are currently rebasing"

**Comment by ElastiLotem** [comment]
At every parent rebase commit, there may be conflicts in the child repo.

Does it make sense to do many rebases for each such commit?

What if the child commit requires a rebase --onto, and not an ordinary
rebase?

I think "rebase" has to be chosen manually due to these concerns -- so it
may make more sense to add --rebase or --merge as a flag.
